---
name: Games-SGF
version: 0.993
author: []
abstract: A general SGF parser
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Data::Dumper: 2.121
  Pod::Coverage: 0.19
  Scalar::Util: 1.14
  Test::More: 0.7
  Test::Pod: 1.26
  Test::Pod::Coverage: 1.08
requires:
  enum: 1.016
configure_requires:
  Module::Build: 0.35
provides:
  Games::SGF:
    file: lib/Games/SGF.pm
    version: 0.993
  Games::SGF::Go:
    file: lib/Games/SGF/Go.pm
    version: 0.993
  Games::SGF::Util:
    file: lib/Games/SGF/Util.pm
    version: 0.993
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
